//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.9

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "apod")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub day: i16,
    #[sea_orm(primary_key, auto_increment = false)]
    pub month: i16,
    #[sea_orm(primary_key, auto_increment = false)]
    pub year: i16,
    pub title: Option<String>,
    pub explanation: Option<String>,
    pub url: Option<String>,
    pub hd_url: Option<String>,
    pub thumbnail_url: Option<String>,
    pub media_type: Option<String>,
    pub copyright: Option<String>,
    pub was_announced: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
