//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.9

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "black_jack_user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: String,
    pub final_hit_score_total: i64,
    pub times_final_hit: i32,
    pub final_stand_score_total: i64,
    pub times_final_stand: i32,
    pub blackjack_count: i32,
    pub blackjack_streak: i32,
    pub longest_blackjack_streak: i32,
    pub wins: i32,
    pub losses: i32,
    pub draws: i32,
    pub win_streak: i32,
    pub longest_win_streak: i32,
    pub loss_streak: i32,
    pub longest_loss_streak: i32,
    pub draw_streak: i32,
    pub longest_draw_streak: i32,
    pub dealer_score_total: i64,
    pub total_citrine_wagered: i64,
    pub total_citrine_won: i64,
    pub total_citrine_lost: i64,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
