//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.9

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "guild")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::guild_birthday::Entity")]
    GuildBirthday,
}

impl Related<super::guild_birthday::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GuildBirthday.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
