//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.9

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "guild_youtube_channel")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub guild_id: String,
    #[sea_orm(primary_key, auto_increment = false)]
    pub channel_id: String,
    pub created_by_user_id: String,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::guild::Entity",
        from = "Column::GuildId",
        to = "super::guild::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Guild,
    #[sea_orm(
        belongs_to = "super::youtube_channel::Entity",
        from = "Column::ChannelId",
        to = "super::youtube_channel::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    YoutubeChannel,
}

impl Related<super::guild::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Guild.def()
    }
}

impl Related<super::youtube_channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::YoutubeChannel.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
