//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.9

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "guild")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::guild_apod::Entity")]
    GuildApod,
    #[sea_orm(has_one = "super::guild_birthday::Entity")]
    GuildBirthday,
    #[sea_orm(has_many = "super::user_guild::Entity")]
    UserGuild,
}

impl Related<super::guild_apod::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GuildApod.def()
    }
}

impl Related<super::guild_birthday::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GuildBirthday.def()
    }
}

impl Related<super::user_guild::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserGuild.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_guild::Relation::User.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_guild::Relation::Guild.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
