//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.9

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub username: Option<String>,
    pub avatar_hash: Option<String>,
    pub encrypted_oauth_token: Option<String>,
    pub permissions: i64,
    pub preferred_timezone: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::black_jack_user::Entity")]
    BlackJackUser,
    #[sea_orm(has_one = "super::farming::Entity")]
    Farming,
    #[sea_orm(has_many = "super::farming_world::Entity")]
    FarmingWorld,
    #[sea_orm(has_many = "super::inventory_item::Entity")]
    InventoryItem,
    #[sea_orm(has_one = "super::rps_user::Entity")]
    RpsUser,
    #[sea_orm(has_one = "super::user_birthday::Entity")]
    UserBirthday,
    #[sea_orm(has_many = "super::user_guild::Entity")]
    UserGuild,
}

impl Related<super::black_jack_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BlackJackUser.def()
    }
}

impl Related<super::farming::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Farming.def()
    }
}

impl Related<super::farming_world::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::FarmingWorld.def()
    }
}

impl Related<super::inventory_item::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::InventoryItem.def()
    }
}

impl Related<super::rps_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RpsUser.def()
    }
}

impl Related<super::user_birthday::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserBirthday.def()
    }
}

impl Related<super::user_guild::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserGuild.def()
    }
}

impl Related<super::guild::Entity> for Entity {
    fn to() -> RelationDef {
        super::user_guild::Relation::Guild.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::user_guild::Relation::User.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
