//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.9

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "youtube_video")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub channel_id: String,
    pub title: Option<String>,
    pub thumbnail_url: Option<String>,
    pub notification_sent: bool,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::youtube_channel::Entity",
        from = "Column::ChannelId",
        to = "super::youtube_channel::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    YoutubeChannel,
}

impl Related<super::youtube_channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::YoutubeChannel.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
