//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0.0-rc.9

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "youtube_channel")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub icon_url: Option<String>,
    pub next_resubscription_at: DateTime,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::guild_youtube_channel::Entity")]
    GuildYoutubeChannel,
    #[sea_orm(has_many = "super::youtube_video::Entity")]
    YoutubeVideo,
}

impl Related<super::guild_youtube_channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GuildYoutubeChannel.def()
    }
}

impl Related<super::youtube_video::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::YoutubeVideo.def()
    }
}

impl Related<super::guild::Entity> for Entity {
    fn to() -> RelationDef {
        super::guild_youtube_channel::Relation::Guild.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::guild_youtube_channel::Relation::YoutubeChannel
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
