FROM rust:1-bookworm

WORKDIR /workspace

RUN apt-get update && apt-get install -y \
    libssl-dev \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN cargo install cargo-watch

CMD ["cargo", "watch", "-x", "run --bin neobabu-web"]