use rand::prelude::IndexedRandom;

#[derive(Debug, Copy, Clone)]
pub enum EmojiType {
    ArrowBack,
    ArrowLeft,
    ArrowRight,
    ArrowDoubleLeft,
    ArrowDoubleRight,
    BalloonRed,
    Clock,
    FaceAngry,
    FaceAngryEvil,
    FaceAnguished,
    FaceAnxiousSweat,
    FaceAstonished,
    FaceBeamingSmile,
    FaceBlowingKiss,
    FaceClouds,
    FaceClown,
    FaceCold,
    FaceConfounded,
    FaceConfusedSad,
    FaceCool,
    FaceCowboyHat,
    FaceCrying,
    FaceCursing,
    FaceDiagonalMouth,
    FaceDisappointed,
    FaceDisguised,
    FaceDizzy,
    FaceDottedLine,
    FaceDowncase,
    FaceDrooling,
    FaceExhaling,
    FaceExploding,
    FaceExpressionless,
    FaceFearful,
    FaceFlushed,
    FaceFrowningOpen,
    FaceFrowningSlight,
    FaceFrowning,
    FaceGrimacing,
    FaceGrinningBigEyes,
    FaceGrinningSmiling,
    FaceGrinningSquinting,
    FaceGrinningSweat,
    FaceGrinning,
    FaceHalo,
    FaceHandOverMouthEyes,
    FaceHandOverMouth,
    FaceHeadBandage,
    FaceHeartEyes,
    FaceHearts,
    FaceHoldingTears,
    FaceHot,
    FaceHugging,
    FaceHushed,
    FaceIll,
    FaceJoyTears,
    FaceKissingClosed,
    FaceKissingSmiling,
    FaceKissing,
    FaceLying,
    FaceMedicalMask,
    FaceMelting,
    FaceMewing,
    FaceMoney,
    FaceMonocle,
    FaceNauseated,
    FaceNerd,
    FaceNeutral,
    FaceNoMouth,
    FaceOpenMouth,
    FacePartying,
    FacePeekingEye,
    FacePensive,
    FacePersevering,
    FacePleading,
    FacePoo,
    FacePouting,
    FaceRaisedEyebrow,
    FaceRelieved,
    FaceRobot,
    FaceRofl,
    FaceRollingEyes,
    FaceSadRelieved,
    FaceSaluting,
    FaceSavoring,
    FaceScreamingFear,
    FaceShakeNo,
    FaceShakeYes,
    FaceShaking,
    FaceShushing,
    FaceSkull,
    FaceSleeping,
    FaceSleepy,
    FaceSmilingBlush,
    FaceSmilingEvil,
    FaceSmilingSlight,
    FaceSmiling,
    FaceSmirking,
    FaceSneezing,
    FaceSobbing,
    FaceSpiralEyes,
    FaceStarStruck,
    FaceTear,
    FaceThinking,
    FaceTired,
    FaceTongueSquinting,
    FaceTongue,
    FaceTriumphant,
    FaceUnamused,
    FaceUpsideDown,
    FaceVomiting,
    FaceWeary,
    FaceWinkingTongue,
    FaceWinking,
    FaceWoozy,
    FaceWorried,
    FaceYawning,
    FaceZany,
    FaceZipperMouth,
    Paper,
    Pvp,
    Rock,
    Scissors,
    Sparkle,
    Trophy,
}

impl EmojiType {
    pub fn name(&self) -> &'static str {
        match self {
            Self::ArrowBack => "arrow_back",
            Self::ArrowLeft => "arrow_left",
            Self::ArrowRight => "arrow_right",
            Self::ArrowDoubleLeft => "arrow_double_left",
            Self::ArrowDoubleRight => "arrow_double_right",
            Self::BalloonRed => "balloon_red",
            Self::Clock => "clock",
            Self::FaceAngry => "face_angry",
            Self::FaceAngryEvil => "face_angry_evil",
            Self::FaceAnguished => "face_anguished",
            Self::FaceAnxiousSweat => "face_anxious_sweat",
            Self::FaceAstonished => "face_astonished",
            Self::FaceBeamingSmile => "face_beaming_smile",
            Self::FaceBlowingKiss => "face_blowing_kiss",
            Self::FaceClouds => "face_clouds",
            Self::FaceClown => "face_clown",
            Self::FaceCold => "face_cold",
            Self::FaceConfounded => "face_confounded",
            Self::FaceConfusedSad => "face_confused_sad",
            Self::FaceCool => "face_cool",
            Self::FaceCowboyHat => "face_cowboy_hat",
            Self::FaceCrying => "face_crying",
            Self::FaceCursing => "face_cursing",
            Self::FaceDiagonalMouth => "face_diagonal_mouth",
            Self::FaceDisappointed => "face_disappointed",
            Self::FaceDisguised => "face_disguised",
            Self::FaceDizzy => "face_dizzy",
            Self::FaceDottedLine => "face_dotted_line",
            Self::FaceDowncase => "face_downcase",
            Self::FaceDrooling => "face_drooling",
            Self::FaceExhaling => "face_exhaling",
            Self::FaceExploding => "face_exploding",
            Self::FaceExpressionless => "face_expressionless",
            Self::FaceFearful => "face_fearful",
            Self::FaceFlushed => "face_flushed",
            Self::FaceFrowningOpen => "face_frowning_open",
            Self::FaceFrowningSlight => "face_frowning_slight",
            Self::FaceFrowning => "face_frowning",
            Self::FaceGrimacing => "face_grimacing",
            Self::FaceGrinningBigEyes => "face_grinning_big_eyes",
            Self::FaceGrinningSmiling => "face_grinning_smiling",
            Self::FaceGrinningSquinting => "face_grinning_squinting",
            Self::FaceGrinningSweat => "face_grinning_sweat",
            Self::FaceGrinning => "face_grinning",
            Self::FaceHalo => "face_halo",
            Self::FaceHandOverMouthEyes => "face_hand_over_mouth_eyes",
            Self::FaceHandOverMouth => "face_hand_over_mouth",
            Self::FaceHeadBandage => "face_head_bandage",
            Self::FaceHeartEyes => "face_heart_eyes",
            Self::FaceHearts => "face_hearts",
            Self::FaceHoldingTears => "face_holding_tears",
            Self::FaceHot => "face_hot",
            Self::FaceHugging => "face_hugging",
            Self::FaceHushed => "face_hushed",
            Self::FaceIll => "face_ill",
            Self::FaceJoyTears => "face_joy_tears",
            Self::FaceKissingClosed => "face_kissing_closed",
            Self::FaceKissingSmiling => "face_kissing_smiling",
            Self::FaceKissing => "face_kissing",
            Self::FaceLying => "face_lying",
            Self::FaceMedicalMask => "face_medical_mask",
            Self::FaceMelting => "face_melting",
            Self::FaceMewing => "face_mewing",
            Self::FaceMoney => "face_money",
            Self::FaceMonocle => "face_monocle",
            Self::FaceNauseated => "face_nauseated",
            Self::FaceNerd => "face_nerd",
            Self::FaceNeutral => "face_neutral",
            Self::FaceNoMouth => "face_no_mouth",
            Self::FaceOpenMouth => "face_open_mouth",
            Self::FacePartying => "face_partying",
            Self::FacePeekingEye => "face_peeking_eye",
            Self::FacePensive => "face_pensive",
            Self::FacePersevering => "face_persevering",
            Self::FacePleading => "face_pleading",
            Self::FacePoo => "face_poo",
            Self::FacePouting => "face_pouting",
            Self::FaceRaisedEyebrow => "face_raised_eyebrow",
            Self::FaceRelieved => "face_relieved",
            Self::FaceRobot => "face_robot",
            Self::FaceRofl => "face_rofl",
            Self::FaceRollingEyes => "face_rolling_eyes",
            Self::FaceSadRelieved => "face_sad_relieved",
            Self::FaceSaluting => "face_saluting",
            Self::FaceSavoring => "face_savoring",
            Self::FaceScreamingFear => "face_screaming_fear",
            Self::FaceShakeNo => "face_shake_no",
            Self::FaceShakeYes => "face_shake_yes",
            Self::FaceShaking => "face_shaking",
            Self::FaceShushing => "face_shushing",
            Self::FaceSkull => "face_skull",
            Self::FaceSleeping => "face_sleeping",
            Self::FaceSleepy => "face_sleepy",
            Self::FaceSmilingBlush => "face_smiling_blush",
            Self::FaceSmilingEvil => "face_smiling_evil",
            Self::FaceSmilingSlight => "face_smiling_slight",
            Self::FaceSmiling => "face_smiling",
            Self::FaceSmirking => "face_smirking",
            Self::FaceSneezing => "face_sneezing",
            Self::FaceSobbing => "face_sobbing",
            Self::FaceSpiralEyes => "face_spiral_eyes",
            Self::FaceStarStruck => "face_star_struck",
            Self::FaceTear => "face_tear",
            Self::FaceThinking => "face_thinking",
            Self::FaceTired => "face_tired",
            Self::FaceTongueSquinting => "face_tongue_squinting",
            Self::FaceTongue => "face_tongue",
            Self::FaceTriumphant => "face_triumphant",
            Self::FaceUnamused => "face_unamused",
            Self::FaceUpsideDown => "face_upside_down",
            Self::FaceVomiting => "face_vomiting",
            Self::FaceWeary => "face_weary",
            Self::FaceWinkingTongue => "face_winking_tongue",
            Self::FaceWinking => "face_winking",
            Self::FaceWoozy => "face_woozy",
            Self::FaceWorried => "face_worried",
            Self::FaceYawning => "face_yawning",
            Self::FaceZany => "face_zany",
            Self::FaceZipperMouth => "face_zipper_mouth",
            Self::Paper => "paper",
            Self::Pvp => "pvp",
            Self::Rock => "rock",
            Self::Scissors => "scissors",
            Self::Sparkle => "sparkle",
            Self::Trophy => "trophy",
        }
    }

    pub fn choices_loser() -> &'static [EmojiType] {
        &[
            Self::FaceAngry,
            Self::FaceAngryEvil,
            Self::FaceAnguished,
            Self::FaceAnxiousSweat,
            Self::FaceClouds,
            Self::FaceClown,
            Self::FaceCold,
            Self::FaceConfounded,
            Self::FaceConfusedSad,
            Self::FaceCrying,
            Self::FaceCursing,
            Self::FaceDiagonalMouth,
            Self::FaceDisappointed,
            Self::FaceDizzy,
            Self::FaceDottedLine,
            Self::FaceDowncase,
            Self::FaceExploding,
            Self::FaceExpressionless,
            Self::FaceFearful,
            Self::FaceFlushed,
            Self::FaceFrowningOpen,
            Self::FaceFrowningSlight,
            Self::FaceFrowning,
            Self::FaceGrimacing,
            Self::FaceHandOverMouthEyes,
            Self::FaceHeadBandage,
            Self::FaceHushed,
            Self::FaceIll,
            Self::FaceLying,
            Self::FaceMedicalMask,
            Self::FaceMelting,
            Self::FaceNauseated,
            Self::FaceNerd,
            Self::FaceNoMouth,
            Self::FaceOpenMouth,
            Self::FacePeekingEye,
            Self::FacePensive,
            Self::FacePersevering,
            Self::FacePleading,
            Self::FacePoo,
            Self::FacePouting,
            Self::FaceRaisedEyebrow,
            Self::FaceRollingEyes,
            Self::FaceSadRelieved,
            Self::FaceScreamingFear,
            Self::FaceShaking,
            Self::FaceSkull,
            Self::FaceSneezing,
            Self::FaceSobbing,
            Self::FaceSpiralEyes,
            Self::FaceTear,
            Self::FaceTired,
            Self::FaceUnamused,
            Self::FaceVomiting,
            Self::FaceWeary,
            Self::FaceWoozy,
            Self::FaceWorried,
            Self::FaceZipperMouth,
        ]
    }

    pub fn random_loser() -> Self {
        let choice = Self::choices_loser().choose(&mut rand::rng()).copied();
        choice.unwrap_or(Self::FaceAngry)
    }

    pub fn choices_winner() -> &'static [EmojiType] {
        &[
            Self::FaceAstonished,
            Self::FaceBeamingSmile,
            Self::FaceBlowingKiss,
            Self::FaceCool,
            Self::FaceCowboyHat,
            Self::FaceDrooling,
            Self::FaceExhaling,
            Self::FaceExploding,
            Self::FaceFlushed,
            Self::FaceGrinningBigEyes,
            Self::FaceGrinningSmiling,
            Self::FaceGrinningSquinting,
            Self::FaceGrinningSweat,
            Self::FaceGrinning,
            Self::FaceHalo,
            Self::FaceHandOverMouthEyes,
            Self::FaceHandOverMouth,
            Self::FaceHeartEyes,
            Self::FaceHearts,
            Self::FaceHoldingTears,
            Self::FaceHot,
            Self::FaceHugging,
            Self::FaceHushed,
            Self::FaceJoyTears,
            Self::FaceKissingClosed,
            Self::FaceKissingSmiling,
            Self::FaceKissing,
            Self::FaceMewing,
            Self::FaceMonocle,
            Self::FaceNerd,
            Self::FaceOpenMouth,
            Self::FacePartying,
            Self::FaceRaisedEyebrow,
            Self::FaceRelieved,
            Self::FaceRofl,
            Self::FaceSaluting,
            Self::FaceSavoring,
            Self::FaceSleeping,
            Self::FaceSleepy,
            Self::FaceSmilingBlush,
            Self::FaceSmilingEvil,
            Self::FaceSmilingSlight,
            Self::FaceSmiling,
            Self::FaceSmirking,
            Self::FaceStarStruck,
            Self::FaceTongueSquinting,
            Self::FaceTongue,
            Self::FaceTriumphant,
            Self::FaceUpsideDown,
            Self::FaceWinkingTongue,
            Self::FaceWinking,
            Self::FaceWoozy,
            Self::FaceYawning,
            Self::FaceZany,
        ]
    }

    pub fn random_winner() -> Self {
        let choice = Self::choices_winner().choose(&mut rand::rng()).copied();
        choice.unwrap_or(Self::FaceAstonished)
    }
}
