use neobabu_core::games::farming::season::Season;
use neobabu_core::games::playing_cards::PlayingCard;
use rand::prelude::IndexedRandom;

#[derive(Debug, Copy, Clone)]
pub enum EmojiType {
    ArrowBack,
    ArrowLeft,
    ArrowRight,
    ArrowDoubleLeft,
    ArrowDoubleRight,
    BalloonRed,
    CardSpades2,
    CardSpades3,
    CardSpades4,
    CardSpades5,
    CardSpades6,
    CardSpades7,
    CardSpades8,
    CardSpades9,
    CardSpades10,
    CardSpadesJ,
    CardSpadesQ,
    CardSpadesK,
    CardSpadesA,
    CardHearts2,
    CardHearts3,
    CardHearts4,
    CardHearts5,
    CardHearts6,
    CardHearts7,
    CardHearts8,
    CardHearts9,
    CardHearts10,
    CardHeartsJ,
    CardHeartsQ,
    CardHeartsK,
    CardHeartsA,
    CardClubs2,
    CardClubs3,
    CardClubs4,
    CardClubs5,
    CardClubs6,
    CardClubs7,
    CardClubs8,
    CardClubs9,
    CardClubs10,
    CardClubsJ,
    CardClubsQ,
    CardClubsK,
    CardClubsA,
    CardDiamonds2,
    CardDiamonds3,
    CardDiamonds4,
    CardDiamonds5,
    CardDiamonds6,
    CardDiamonds7,
    CardDiamonds8,
    CardDiamonds9,
    CardDiamonds10,
    CardDiamondsJ,
    CardDiamondsQ,
    CardDiamondsK,
    CardDiamondsA,
    Clock,
    FaceAngry,
    FaceAngryEvil,
    FaceAnguished,
    FaceAnxiousSweat,
    FaceAstonished,
    FaceBeamingSmile,
    FaceBlowingKiss,
    FaceClouds,
    FaceClown,
    FaceCold,
    FaceConfounded,
    FaceConfusedSad,
    FaceCool,
    FaceCowboyHat,
    FaceCrying,
    FaceCursing,
    FaceDiagonalMouth,
    FaceDisappointed,
    FaceDisguised,
    FaceDizzy,
    FaceDottedLine,
    FaceDowncase,
    FaceDrooling,
    FaceExhaling,
    FaceExploding,
    FaceExpressionless,
    FaceFearful,
    FaceFlushed,
    FaceFrowningOpen,
    FaceFrowningSlight,
    FaceFrowning,
    FaceGrimacing,
    FaceGrinningBigEyes,
    FaceGrinningSmiling,
    FaceGrinningSquinting,
    FaceGrinningSweat,
    FaceGrinning,
    FaceHalo,
    FaceHandOverMouthEyes,
    FaceHandOverMouth,
    FaceHeadBandage,
    FaceHeartEyes,
    FaceHearts,
    FaceHoldingTears,
    FaceHot,
    FaceHugging,
    FaceHushed,
    FaceIll,
    FaceJoyTears,
    FaceKissingClosed,
    FaceKissingSmiling,
    FaceKissing,
    FaceLying,
    FaceMedicalMask,
    FaceMelting,
    FaceMewing,
    FaceMoney,
    FaceMonocle,
    FaceNauseated,
    FaceNerd,
    FaceNeutral,
    FaceNoMouth,
    FaceOpenMouth,
    FacePartying,
    FacePeekingEye,
    FacePensive,
    FacePersevering,
    FacePleading,
    FacePoo,
    FacePouting,
    FaceRaisedEyebrow,
    FaceRelieved,
    FaceRobot,
    FaceRofl,
    FaceRollingEyes,
    FaceSadRelieved,
    FaceSaluting,
    FaceSavoring,
    FaceScreamingFear,
    FaceShakeNo,
    FaceShakeYes,
    FaceShaking,
    FaceShushing,
    FaceSkull,
    FaceSleeping,
    FaceSleepy,
    FaceSmilingBlush,
    FaceSmilingEvil,
    FaceSmilingSlight,
    FaceSmiling,
    FaceSmirking,
    FaceSneezing,
    FaceSobbing,
    FaceSpiralEyes,
    FaceStarStruck,
    FaceTear,
    FaceThinking,
    FaceTired,
    FaceTongueSquinting,
    FaceTongue,
    FaceTriumphant,
    FaceUnamused,
    FaceUpsideDown,
    FaceVomiting,
    FaceWeary,
    FaceWinkingTongue,
    FaceWinking,
    FaceWoozy,
    FaceWorried,
    FaceYawning,
    FaceZany,
    FaceZipperMouth,
    Friends,
    MapleLeaf,
    Paper,
    PurpleFlower,
    Pvp,
    Rock,
    Scissors,
    Snowflake,
    Sparkle,
    Stats,
    Sun,
    Trophy,
}

impl EmojiType {
    pub fn name(&self) -> &'static str {
        match self {
            Self::ArrowBack => "arrow_back",
            Self::ArrowLeft => "arrow_left",
            Self::ArrowRight => "arrow_right",
            Self::ArrowDoubleLeft => "arrow_double_left",
            Self::ArrowDoubleRight => "arrow_double_right",
            Self::BalloonRed => "balloon_red",
            Self::CardSpades2 => "card_s_2",
            Self::CardSpades3 => "card_s_3",
            Self::CardSpades4 => "card_s_4",
            Self::CardSpades5 => "card_s_5",
            Self::CardSpades6 => "card_s_6",
            Self::CardSpades7 => "card_s_7",
            Self::CardSpades8 => "card_s_8",
            Self::CardSpades9 => "card_s_9",
            Self::CardSpades10 => "card_s_10",
            Self::CardSpadesJ => "card_s_j",
            Self::CardSpadesQ => "card_s_q",
            Self::CardSpadesK => "card_s_k",
            Self::CardSpadesA => "card_s_a",
            Self::CardHearts2 => "card_h_2",
            Self::CardHearts3 => "card_h_3",
            Self::CardHearts4 => "card_h_4",
            Self::CardHearts5 => "card_h_5",
            Self::CardHearts6 => "card_h_6",
            Self::CardHearts7 => "card_h_7",
            Self::CardHearts8 => "card_h_8",
            Self::CardHearts9 => "card_h_9",
            Self::CardHearts10 => "card_h_10",
            Self::CardHeartsJ => "card_h_j",
            Self::CardHeartsQ => "card_h_q",
            Self::CardHeartsK => "card_h_k",
            Self::CardHeartsA => "card_h_a",
            Self::CardClubs2 => "card_c_2",
            Self::CardClubs3 => "card_c_3",
            Self::CardClubs4 => "card_c_4",
            Self::CardClubs5 => "card_c_5",
            Self::CardClubs6 => "card_c_6",
            Self::CardClubs7 => "card_c_7",
            Self::CardClubs8 => "card_c_8",
            Self::CardClubs9 => "card_c_9",
            Self::CardClubs10 => "card_c_10",
            Self::CardClubsJ => "card_c_j",
            Self::CardClubsQ => "card_c_q",
            Self::CardClubsK => "card_c_k",
            Self::CardClubsA => "card_c_a",
            Self::CardDiamonds2 => "card_d_2",
            Self::CardDiamonds3 => "card_d_3",
            Self::CardDiamonds4 => "card_d_4",
            Self::CardDiamonds5 => "card_d_5",
            Self::CardDiamonds6 => "card_d_6",
            Self::CardDiamonds7 => "card_d_7",
            Self::CardDiamonds8 => "card_d_8",
            Self::CardDiamonds9 => "card_d_9",
            Self::CardDiamonds10 => "card_d_10",
            Self::CardDiamondsJ => "card_d_j",
            Self::CardDiamondsQ => "card_d_q",
            Self::CardDiamondsK => "card_d_k",
            Self::CardDiamondsA => "card_d_a",
            Self::Clock => "clock",
            Self::FaceAngry => "face_angry",
            Self::FaceAngryEvil => "face_angry_evil",
            Self::FaceAnguished => "face_anguished",
            Self::FaceAnxiousSweat => "face_anxious_sweat",
            Self::FaceAstonished => "face_astonished",
            Self::FaceBeamingSmile => "face_beaming_smile",
            Self::FaceBlowingKiss => "face_blowing_kiss",
            Self::FaceClouds => "face_clouds",
            Self::FaceClown => "face_clown",
            Self::FaceCold => "face_cold",
            Self::FaceConfounded => "face_confounded",
            Self::FaceConfusedSad => "face_confused_sad",
            Self::FaceCool => "face_cool",
            Self::FaceCowboyHat => "face_cowboy_hat",
            Self::FaceCrying => "face_crying",
            Self::FaceCursing => "face_cursing",
            Self::FaceDiagonalMouth => "face_diagonal_mouth",
            Self::FaceDisappointed => "face_disappointed",
            Self::FaceDisguised => "face_disguised",
            Self::FaceDizzy => "face_dizzy",
            Self::FaceDottedLine => "face_dotted_line",
            Self::FaceDowncase => "face_downcase",
            Self::FaceDrooling => "face_drooling",
            Self::FaceExhaling => "face_exhaling",
            Self::FaceExploding => "face_exploding",
            Self::FaceExpressionless => "face_expressionless",
            Self::FaceFearful => "face_fearful",
            Self::FaceFlushed => "face_flushed",
            Self::FaceFrowningOpen => "face_frowning_open",
            Self::FaceFrowningSlight => "face_frowning_slight",
            Self::FaceFrowning => "face_frowning",
            Self::FaceGrimacing => "face_grimacing",
            Self::FaceGrinningBigEyes => "face_grinning_big_eyes",
            Self::FaceGrinningSmiling => "face_grinning_smiling",
            Self::FaceGrinningSquinting => "face_grinning_squinting",
            Self::FaceGrinningSweat => "face_grinning_sweat",
            Self::FaceGrinning => "face_grinning",
            Self::FaceHalo => "face_halo",
            Self::FaceHandOverMouthEyes => "face_hand_over_mouth_eyes",
            Self::FaceHandOverMouth => "face_hand_over_mouth",
            Self::FaceHeadBandage => "face_head_bandage",
            Self::FaceHeartEyes => "face_heart_eyes",
            Self::FaceHearts => "face_hearts",
            Self::FaceHoldingTears => "face_holding_tears",
            Self::FaceHot => "face_hot",
            Self::FaceHugging => "face_hugging",
            Self::FaceHushed => "face_hushed",
            Self::FaceIll => "face_ill",
            Self::FaceJoyTears => "face_joy_tears",
            Self::FaceKissingClosed => "face_kissing_closed",
            Self::FaceKissingSmiling => "face_kissing_smiling",
            Self::FaceKissing => "face_kissing",
            Self::FaceLying => "face_lying",
            Self::FaceMedicalMask => "face_medical_mask",
            Self::FaceMelting => "face_melting",
            Self::FaceMewing => "face_mewing",
            Self::FaceMoney => "face_money",
            Self::FaceMonocle => "face_monocle",
            Self::FaceNauseated => "face_nauseated",
            Self::FaceNerd => "face_nerd",
            Self::FaceNeutral => "face_neutral",
            Self::FaceNoMouth => "face_no_mouth",
            Self::FaceOpenMouth => "face_open_mouth",
            Self::FacePartying => "face_partying",
            Self::FacePeekingEye => "face_peeking_eye",
            Self::FacePensive => "face_pensive",
            Self::FacePersevering => "face_persevering",
            Self::FacePleading => "face_pleading",
            Self::FacePoo => "face_poo",
            Self::FacePouting => "face_pouting",
            Self::FaceRaisedEyebrow => "face_raised_eyebrow",
            Self::FaceRelieved => "face_relieved",
            Self::FaceRobot => "face_robot",
            Self::FaceRofl => "face_rofl",
            Self::FaceRollingEyes => "face_rolling_eyes",
            Self::FaceSadRelieved => "face_sad_relieved",
            Self::FaceSaluting => "face_saluting",
            Self::FaceSavoring => "face_savoring",
            Self::FaceScreamingFear => "face_screaming_fear",
            Self::FaceShakeNo => "face_shake_no",
            Self::FaceShakeYes => "face_shake_yes",
            Self::FaceShaking => "face_shaking",
            Self::FaceShushing => "face_shushing",
            Self::FaceSkull => "face_skull",
            Self::FaceSleeping => "face_sleeping",
            Self::FaceSleepy => "face_sleepy",
            Self::FaceSmilingBlush => "face_smiling_blush",
            Self::FaceSmilingEvil => "face_smiling_evil",
            Self::FaceSmilingSlight => "face_smiling_slight",
            Self::FaceSmiling => "face_smiling",
            Self::FaceSmirking => "face_smirking",
            Self::FaceSneezing => "face_sneezing",
            Self::FaceSobbing => "face_sobbing",
            Self::FaceSpiralEyes => "face_spiral_eyes",
            Self::FaceStarStruck => "face_star_struck",
            Self::FaceTear => "face_tear",
            Self::FaceThinking => "face_thinking",
            Self::FaceTired => "face_tired",
            Self::FaceTongueSquinting => "face_tongue_squinting",
            Self::FaceTongue => "face_tongue",
            Self::FaceTriumphant => "face_triumphant",
            Self::FaceUnamused => "face_unamused",
            Self::FaceUpsideDown => "face_upside_down",
            Self::FaceVomiting => "face_vomiting",
            Self::FaceWeary => "face_weary",
            Self::FaceWinkingTongue => "face_winking_tongue",
            Self::FaceWinking => "face_winking",
            Self::FaceWoozy => "face_woozy",
            Self::FaceWorried => "face_worried",
            Self::FaceYawning => "face_yawning",
            Self::FaceZany => "face_zany",
            Self::FaceZipperMouth => "face_zipper_mouth",
            Self::Friends => "friends",
            Self::MapleLeaf => "maple_leaf",
            Self::Paper => "paper",
            Self::PurpleFlower => "purple_flower",
            Self::Pvp => "pvp",
            Self::Rock => "rock",
            Self::Scissors => "scissors",
            Self::Snowflake => "snowflake",
            Self::Sparkle => "sparkle",
            Self::Stats => "stats",
            Self::Sun => "sun",
            Self::Trophy => "trophy",
        }
    }

    pub fn choices_loser() -> &'static [EmojiType] {
        &[
            Self::FaceAngry,
            Self::FaceAngryEvil,
            Self::FaceAnguished,
            Self::FaceAnxiousSweat,
            Self::FaceClouds,
            Self::FaceClown,
            Self::FaceCold,
            Self::FaceConfounded,
            Self::FaceConfusedSad,
            Self::FaceCrying,
            Self::FaceCursing,
            Self::FaceDiagonalMouth,
            Self::FaceDisappointed,
            Self::FaceDizzy,
            Self::FaceDottedLine,
            Self::FaceDowncase,
            Self::FaceExploding,
            Self::FaceExpressionless,
            Self::FaceFearful,
            Self::FaceFlushed,
            Self::FaceFrowningOpen,
            Self::FaceFrowningSlight,
            Self::FaceFrowning,
            Self::FaceGrimacing,
            Self::FaceHandOverMouthEyes,
            Self::FaceHeadBandage,
            Self::FaceHushed,
            Self::FaceIll,
            Self::FaceLying,
            Self::FaceMedicalMask,
            Self::FaceMelting,
            Self::FaceNauseated,
            Self::FaceNerd,
            Self::FaceNoMouth,
            Self::FaceOpenMouth,
            Self::FacePeekingEye,
            Self::FacePensive,
            Self::FacePersevering,
            Self::FacePleading,
            Self::FacePoo,
            Self::FacePouting,
            Self::FaceRaisedEyebrow,
            Self::FaceRollingEyes,
            Self::FaceSadRelieved,
            Self::FaceScreamingFear,
            Self::FaceShaking,
            Self::FaceSkull,
            Self::FaceSneezing,
            Self::FaceSobbing,
            Self::FaceSpiralEyes,
            Self::FaceTear,
            Self::FaceTired,
            Self::FaceUnamused,
            Self::FaceVomiting,
            Self::FaceWeary,
            Self::FaceWoozy,
            Self::FaceWorried,
            Self::FaceZipperMouth,
        ]
    }

    pub fn random_loser() -> Self {
        let choice = Self::choices_loser().choose(&mut rand::rng()).copied();
        choice.unwrap_or(Self::FaceAngry)
    }

    pub fn choices_winner() -> &'static [EmojiType] {
        &[
            Self::FaceAstonished,
            Self::FaceBeamingSmile,
            Self::FaceBlowingKiss,
            Self::FaceCool,
            Self::FaceCowboyHat,
            Self::FaceDrooling,
            Self::FaceExhaling,
            Self::FaceExploding,
            Self::FaceFlushed,
            Self::FaceGrinningBigEyes,
            Self::FaceGrinningSmiling,
            Self::FaceGrinningSquinting,
            Self::FaceGrinningSweat,
            Self::FaceGrinning,
            Self::FaceHalo,
            Self::FaceHandOverMouthEyes,
            Self::FaceHandOverMouth,
            Self::FaceHeartEyes,
            Self::FaceHearts,
            Self::FaceHoldingTears,
            Self::FaceHot,
            Self::FaceHugging,
            Self::FaceHushed,
            Self::FaceJoyTears,
            Self::FaceKissingClosed,
            Self::FaceKissingSmiling,
            Self::FaceKissing,
            Self::FaceMewing,
            Self::FaceMonocle,
            Self::FaceNerd,
            Self::FaceOpenMouth,
            Self::FacePartying,
            Self::FaceRaisedEyebrow,
            Self::FaceRelieved,
            Self::FaceRofl,
            Self::FaceSaluting,
            Self::FaceSavoring,
            Self::FaceSleeping,
            Self::FaceSleepy,
            Self::FaceSmilingBlush,
            Self::FaceSmilingEvil,
            Self::FaceSmilingSlight,
            Self::FaceSmiling,
            Self::FaceSmirking,
            Self::FaceStarStruck,
            Self::FaceTongueSquinting,
            Self::FaceTongue,
            Self::FaceTriumphant,
            Self::FaceUpsideDown,
            Self::FaceWinkingTongue,
            Self::FaceWinking,
            Self::FaceWoozy,
            Self::FaceYawning,
            Self::FaceZany,
        ]
    }

    pub fn random_winner() -> Self {
        let choice = Self::choices_winner().choose(&mut rand::rng()).copied();
        choice.unwrap_or(Self::FaceAstonished)
    }

    pub fn choices_waiting() -> &'static [EmojiType] {
        &[
            Self::FaceBeamingSmile,
            Self::FaceCool,
            Self::FaceCowboyHat,
            Self::FaceDisguised,
            Self::FaceExpressionless,
            Self::FaceGrimacing,
            Self::FaceGrinningSmiling,
            Self::FaceHalo,
            Self::FaceHandOverMouth,
            Self::FaceHearts,
            Self::FaceMewing,
            Self::FaceMoney,
            Self::FaceMonocle,
            Self::FaceNerd,
            Self::FaceNeutral,
            Self::FacePeekingEye,
            Self::FaceRelieved,
            Self::FaceRollingEyes,
            Self::FaceSaluting,
            Self::FaceSavoring,
            Self::FaceShakeNo,
            Self::FaceShakeYes,
            Self::FaceShushing,
            Self::FaceSleeping,
            Self::FaceSmilingBlush,
            Self::FaceSmilingEvil,
            Self::FaceSmilingSlight,
            Self::FaceSmiling,
            Self::FaceSmirking,
            Self::FaceThinking,
            Self::FaceTriumphant,
            Self::FaceUpsideDown,
            Self::FaceWinkingTongue,
            Self::FaceWinking,
            Self::FaceWoozy,
            Self::FaceYawning,
            Self::FaceZany,
            Self::FaceZipperMouth,
        ]
    }

    pub fn random_waiting() -> Self {
        let choice = Self::choices_waiting().choose(&mut rand::rng()).copied();
        choice.unwrap_or(Self::FaceBeamingSmile)
    }

    pub fn choices_professional() -> &'static [EmojiType] {
        &[
            Self::FaceBeamingSmile,
            Self::FaceGrinningSmiling,
            Self::FaceSmilingBlush,
            Self::FaceSmilingSlight,
            Self::FaceSmiling,
        ]
    }

    pub fn random_professional() -> Self {
        let choice = Self::choices_professional()
            .choose(&mut rand::rng())
            .copied();
        choice.unwrap_or(Self::FaceBeamingSmile)
    }
}

impl From<Season> for EmojiType {
    fn from(value: Season) -> Self {
        match value {
            Season::Spring => Self::PurpleFlower,
            Season::Summer => Self::Sun,
            Season::Autumn => Self::MapleLeaf,
            Season::Winter => Self::Snowflake,
        }
    }
}

impl From<PlayingCard> for EmojiType {
    fn from(value: PlayingCard) -> Self {
        match value {
            PlayingCard::Spades2 => Self::CardSpades2,
            PlayingCard::Spades3 => Self::CardSpades3,
            PlayingCard::Spades4 => Self::CardSpades4,
            PlayingCard::Spades5 => Self::CardSpades5,
            PlayingCard::Spades6 => Self::CardSpades6,
            PlayingCard::Spades7 => Self::CardSpades7,
            PlayingCard::Spades8 => Self::CardSpades8,
            PlayingCard::Spades9 => Self::CardSpades9,
            PlayingCard::Spades10 => Self::CardSpades10,
            PlayingCard::SpadesJack => Self::CardSpadesJ,
            PlayingCard::SpadesQueen => Self::CardSpadesQ,
            PlayingCard::SpadesKing => Self::CardSpadesK,
            PlayingCard::SpadesAce => Self::CardSpadesA,
            PlayingCard::Hearts2 => Self::CardHearts2,
            PlayingCard::Hearts3 => Self::CardHearts3,
            PlayingCard::Hearts4 => Self::CardHearts4,
            PlayingCard::Hearts5 => Self::CardHearts5,
            PlayingCard::Hearts6 => Self::CardHearts6,
            PlayingCard::Hearts7 => Self::CardHearts7,
            PlayingCard::Hearts8 => Self::CardHearts8,
            PlayingCard::Hearts9 => Self::CardHearts9,
            PlayingCard::Hearts10 => Self::CardHearts10,
            PlayingCard::HeartsJack => Self::CardHeartsJ,
            PlayingCard::HeartsQueen => Self::CardHeartsQ,
            PlayingCard::HeartsKing => Self::CardHeartsK,
            PlayingCard::HeartsAce => Self::CardHeartsA,
            PlayingCard::Clubs2 => Self::CardClubs2,
            PlayingCard::Clubs3 => Self::CardClubs3,
            PlayingCard::Clubs4 => Self::CardClubs4,
            PlayingCard::Clubs5 => Self::CardClubs5,
            PlayingCard::Clubs6 => Self::CardClubs6,
            PlayingCard::Clubs7 => Self::CardClubs7,
            PlayingCard::Clubs8 => Self::CardClubs8,
            PlayingCard::Clubs9 => Self::CardClubs9,
            PlayingCard::Clubs10 => Self::CardClubs10,
            PlayingCard::ClubsJack => Self::CardClubsJ,
            PlayingCard::ClubsQueen => Self::CardClubsQ,
            PlayingCard::ClubsKing => Self::CardClubsK,
            PlayingCard::ClubsAce => Self::CardClubsA,
            PlayingCard::Diamonds2 => Self::CardDiamonds2,
            PlayingCard::Diamonds3 => Self::CardDiamonds3,
            PlayingCard::Diamonds4 => Self::CardDiamonds4,
            PlayingCard::Diamonds5 => Self::CardDiamonds5,
            PlayingCard::Diamonds6 => Self::CardDiamonds6,
            PlayingCard::Diamonds7 => Self::CardDiamonds7,
            PlayingCard::Diamonds8 => Self::CardDiamonds8,
            PlayingCard::Diamonds9 => Self::CardDiamonds9,
            PlayingCard::Diamonds10 => Self::CardDiamonds10,
            PlayingCard::DiamondsJack => Self::CardDiamondsJ,
            PlayingCard::DiamondsQueen => Self::CardDiamondsQ,
            PlayingCard::DiamondsKing => Self::CardDiamondsK,
            PlayingCard::DiamondsAce => Self::CardDiamondsA,
        }
    }
}
